### ISSUE TITLE
ssh-agent: command not found when using ssh uri

### ISSUE THREAD

**Issue by tomstagg** [aoldershaw/git-branches-resource#1]
When using an SSH URI I get this: 

```
/opt/resource/common.sh: line 15: ssh-agent: command not found
/opt/resource/common.sh: line 16: SSH_AGENT_PID: unbound variable
```

The docker image doesn't contain: openssh-client

**Comment by thewire247** [comment]
This can be resolved by adding 
openssh-client-default
openssh-client-common

To the apk add command in the Dockerfile

**Comment by thewire247** [comment]
PR https://github.com/aoldershaw/git-branches-resource/pull/2 raised

**Comment by aoldershaw** [comment]
Thanks for opening the issue and thanks @thewire247 for the quick fix! Pushed a new image with the fix
